export enum UserRole {
  ELEVEUR= "ELEVEUR",
  INSEMINATEUR = "INSEMINATEUR",
  IDENTIFICATEUR = "IDENTIFICATEUR",
  CONTROLEUR_LAITIER = "CONTROLEUR_LAITIER",
  RESPONSABLE_LOCAL = "RESPONSABLE_LOCAL",
  ADMIN = "ADMIN",
}
